//! AST node `type` discriminator. Ports `ts/src/parser/ast-type.ts`.
//!
//! Lives in `unsnarl-ir` rather than `unsnarl-boundary-eslint-scope` (the
//! crate that will house `parser/` in Step 8) because the IR contract
//! types reference it.
//!
//! The variant list mirrors the union of TS `AST_TYPE` and
//! `AST_TYPE_UNREACHABLE` (the second group being node `type`s that
//! `@oxc-project/types` declares but `parseSync` cannot reach in
//! practice). They are kept in one Rust enum because TS folds both into
//! its `astType$` picklist, and downstream serialization treats them
//! identically.

use serde::Serialize;

pub const UNKNOWN_AST_TYPE: &str = "UnknownAstType";

#[derive(Serialize)]
pub enum AstType {
    AccessorProperty,
    ArrayExpression,
    ArrayPattern,
    ArrowFunctionExpression,
    AssignmentExpression,
    AssignmentPattern,
    AwaitExpression,
    BinaryExpression,
    BlockStatement,
    BreakStatement,
    CallExpression,
    CatchClause,
    ChainExpression,
    ClassBody,
    ClassDeclaration,
    ClassExpression,
    ConditionalExpression,
    ContinueStatement,
    DebuggerStatement,
    Decorator,
    DoWhileStatement,
    EmptyStatement,
    ExportAllDeclaration,
    ExportDefaultDeclaration,
    ExportNamedDeclaration,
    ExportSpecifier,
    ExpressionStatement,
    ForInStatement,
    ForOfStatement,
    ForStatement,
    FunctionDeclaration,
    FunctionExpression,
    Identifier,
    IfStatement,
    ImportAttribute,
    ImportDeclaration,
    ImportDefaultSpecifier,
    ImportExpression,
    ImportNamespaceSpecifier,
    ImportSpecifier,
    JSXAttribute,
    JSXClosingElement,
    JSXClosingFragment,
    JSXElement,
    JSXEmptyExpression,
    JSXExpressionContainer,
    JSXFragment,
    JSXIdentifier,
    JSXMemberExpression,
    JSXNamespacedName,
    JSXOpeningElement,
    JSXOpeningFragment,
    JSXSpreadAttribute,
    JSXSpreadChild,
    JSXText,
    LabeledStatement,
    Literal,
    LogicalExpression,
    MemberExpression,
    MetaProperty,
    MethodDefinition,
    NewExpression,
    ObjectExpression,
    ObjectPattern,
    ParenthesizedExpression,
    PrivateIdentifier,
    Program,
    Property,
    PropertyDefinition,
    RestElement,
    ReturnStatement,
    SequenceExpression,
    SpreadElement,
    StaticBlock,
    Super,
    SwitchCase,
    SwitchStatement,
    TaggedTemplateExpression,
    TemplateElement,
    TemplateLiteral,
    ThisExpression,
    ThrowStatement,
    TryStatement,
    TSAbstractAccessorProperty,
    TSAbstractMethodDefinition,
    TSAbstractPropertyDefinition,
    TSAnyKeyword,
    TSArrayType,
    TSAsExpression,
    TSBigIntKeyword,
    TSBooleanKeyword,
    TSCallSignatureDeclaration,
    TSClassImplements,
    TSConditionalType,
    TSConstructorType,
    TSConstructSignatureDeclaration,
    TSDeclareFunction,
    TSEmptyBodyFunctionExpression,
    TSEnumBody,
    TSEnumDeclaration,
    TSEnumMember,
    TSExportAssignment,
    TSExternalModuleReference,
    TSFunctionType,
    TSImportEqualsDeclaration,
    TSImportType,
    TSIndexedAccessType,
    TSIndexSignature,
    TSInferType,
    TSInstantiationExpression,
    TSInterfaceBody,
    TSInterfaceDeclaration,
    TSInterfaceHeritage,
    TSIntersectionType,
    TSIntrinsicKeyword,
    TSJSDocNonNullableType,
    TSJSDocNullableType,
    TSLiteralType,
    TSMappedType,
    TSMethodSignature,
    TSModuleBlock,
    TSModuleDeclaration,
    TSNamedTupleMember,
    TSNamespaceExportDeclaration,
    TSNeverKeyword,
    TSNonNullExpression,
    TSNullKeyword,
    TSNumberKeyword,
    TSObjectKeyword,
    TSOptionalType,
    TSParameterProperty,
    TSParenthesizedType,
    TSPropertySignature,
    TSQualifiedName,
    TSRestType,
    TSSatisfiesExpression,
    TSStringKeyword,
    TSSymbolKeyword,
    TSTemplateLiteralType,
    TSThisType,
    TSTupleType,
    TSTypeAliasDeclaration,
    TSTypeAnnotation,
    TSTypeAssertion,
    TSTypeLiteral,
    TSTypeOperator,
    TSTypeParameter,
    TSTypeParameterDeclaration,
    TSTypeParameterInstantiation,
    TSTypePredicate,
    TSTypeQuery,
    TSTypeReference,
    TSUndefinedKeyword,
    TSUnionType,
    TSUnknownKeyword,
    TSVoidKeyword,
    UnaryExpression,
    UpdateExpression,
    VariableDeclaration,
    VariableDeclarator,
    WhileStatement,
    WithStatement,
    YieldExpression,
    // AST_TYPE_UNREACHABLE: declared by `@oxc-project/types` but
    // unreachable through `parseSync` -> walker descent.
    Hashbang,
    TSJSDocUnknownType,
    V8IntrinsicExpression,
    // Internal sentinel for parser strings we don't recognize.
    #[serde(rename = "UnknownAstType")]
    UnknownAstType,
}

/// Application-layer normalizer. Maps a raw oxc-parser `type` string to
/// `AstType`, collapsing any unrecognized value to `UnknownAstType`.
/// Ports the `asAstType` function from
/// `ts/src/parser/ast-type.ts`.
pub fn as_ast_type(raw: &str) -> AstType {
    match raw {
        "AccessorProperty" => AstType::AccessorProperty,
        "ArrayExpression" => AstType::ArrayExpression,
        "ArrayPattern" => AstType::ArrayPattern,
        "ArrowFunctionExpression" => AstType::ArrowFunctionExpression,
        "AssignmentExpression" => AstType::AssignmentExpression,
        "AssignmentPattern" => AstType::AssignmentPattern,
        "AwaitExpression" => AstType::AwaitExpression,
        "BinaryExpression" => AstType::BinaryExpression,
        "BlockStatement" => AstType::BlockStatement,
        "BreakStatement" => AstType::BreakStatement,
        "CallExpression" => AstType::CallExpression,
        "CatchClause" => AstType::CatchClause,
        "ChainExpression" => AstType::ChainExpression,
        "ClassBody" => AstType::ClassBody,
        "ClassDeclaration" => AstType::ClassDeclaration,
        "ClassExpression" => AstType::ClassExpression,
        "ConditionalExpression" => AstType::ConditionalExpression,
        "ContinueStatement" => AstType::ContinueStatement,
        "DebuggerStatement" => AstType::DebuggerStatement,
        "Decorator" => AstType::Decorator,
        "DoWhileStatement" => AstType::DoWhileStatement,
        "EmptyStatement" => AstType::EmptyStatement,
        "ExportAllDeclaration" => AstType::ExportAllDeclaration,
        "ExportDefaultDeclaration" => AstType::ExportDefaultDeclaration,
        "ExportNamedDeclaration" => AstType::ExportNamedDeclaration,
        "ExportSpecifier" => AstType::ExportSpecifier,
        "ExpressionStatement" => AstType::ExpressionStatement,
        "ForInStatement" => AstType::ForInStatement,
        "ForOfStatement" => AstType::ForOfStatement,
        "ForStatement" => AstType::ForStatement,
        "FunctionDeclaration" => AstType::FunctionDeclaration,
        "FunctionExpression" => AstType::FunctionExpression,
        "Identifier" => AstType::Identifier,
        "IfStatement" => AstType::IfStatement,
        "ImportAttribute" => AstType::ImportAttribute,
        "ImportDeclaration" => AstType::ImportDeclaration,
        "ImportDefaultSpecifier" => AstType::ImportDefaultSpecifier,
        "ImportExpression" => AstType::ImportExpression,
        "ImportNamespaceSpecifier" => AstType::ImportNamespaceSpecifier,
        "ImportSpecifier" => AstType::ImportSpecifier,
        "JSXAttribute" => AstType::JSXAttribute,
        "JSXClosingElement" => AstType::JSXClosingElement,
        "JSXClosingFragment" => AstType::JSXClosingFragment,
        "JSXElement" => AstType::JSXElement,
        "JSXEmptyExpression" => AstType::JSXEmptyExpression,
        "JSXExpressionContainer" => AstType::JSXExpressionContainer,
        "JSXFragment" => AstType::JSXFragment,
        "JSXIdentifier" => AstType::JSXIdentifier,
        "JSXMemberExpression" => AstType::JSXMemberExpression,
        "JSXNamespacedName" => AstType::JSXNamespacedName,
        "JSXOpeningElement" => AstType::JSXOpeningElement,
        "JSXOpeningFragment" => AstType::JSXOpeningFragment,
        "JSXSpreadAttribute" => AstType::JSXSpreadAttribute,
        "JSXSpreadChild" => AstType::JSXSpreadChild,
        "JSXText" => AstType::JSXText,
        "LabeledStatement" => AstType::LabeledStatement,
        "Literal" => AstType::Literal,
        "LogicalExpression" => AstType::LogicalExpression,
        "MemberExpression" => AstType::MemberExpression,
        "MetaProperty" => AstType::MetaProperty,
        "MethodDefinition" => AstType::MethodDefinition,
        "NewExpression" => AstType::NewExpression,
        "ObjectExpression" => AstType::ObjectExpression,
        "ObjectPattern" => AstType::ObjectPattern,
        "ParenthesizedExpression" => AstType::ParenthesizedExpression,
        "PrivateIdentifier" => AstType::PrivateIdentifier,
        "Program" => AstType::Program,
        "Property" => AstType::Property,
        "PropertyDefinition" => AstType::PropertyDefinition,
        "RestElement" => AstType::RestElement,
        "ReturnStatement" => AstType::ReturnStatement,
        "SequenceExpression" => AstType::SequenceExpression,
        "SpreadElement" => AstType::SpreadElement,
        "StaticBlock" => AstType::StaticBlock,
        "Super" => AstType::Super,
        "SwitchCase" => AstType::SwitchCase,
        "SwitchStatement" => AstType::SwitchStatement,
        "TaggedTemplateExpression" => AstType::TaggedTemplateExpression,
        "TemplateElement" => AstType::TemplateElement,
        "TemplateLiteral" => AstType::TemplateLiteral,
        "ThisExpression" => AstType::ThisExpression,
        "ThrowStatement" => AstType::ThrowStatement,
        "TryStatement" => AstType::TryStatement,
        "TSAbstractAccessorProperty" => AstType::TSAbstractAccessorProperty,
        "TSAbstractMethodDefinition" => AstType::TSAbstractMethodDefinition,
        "TSAbstractPropertyDefinition" => AstType::TSAbstractPropertyDefinition,
        "TSAnyKeyword" => AstType::TSAnyKeyword,
        "TSArrayType" => AstType::TSArrayType,
        "TSAsExpression" => AstType::TSAsExpression,
        "TSBigIntKeyword" => AstType::TSBigIntKeyword,
        "TSBooleanKeyword" => AstType::TSBooleanKeyword,
        "TSCallSignatureDeclaration" => AstType::TSCallSignatureDeclaration,
        "TSClassImplements" => AstType::TSClassImplements,
        "TSConditionalType" => AstType::TSConditionalType,
        "TSConstructorType" => AstType::TSConstructorType,
        "TSConstructSignatureDeclaration" => AstType::TSConstructSignatureDeclaration,
        "TSDeclareFunction" => AstType::TSDeclareFunction,
        "TSEmptyBodyFunctionExpression" => AstType::TSEmptyBodyFunctionExpression,
        "TSEnumBody" => AstType::TSEnumBody,
        "TSEnumDeclaration" => AstType::TSEnumDeclaration,
        "TSEnumMember" => AstType::TSEnumMember,
        "TSExportAssignment" => AstType::TSExportAssignment,
        "TSExternalModuleReference" => AstType::TSExternalModuleReference,
        "TSFunctionType" => AstType::TSFunctionType,
        "TSImportEqualsDeclaration" => AstType::TSImportEqualsDeclaration,
        "TSImportType" => AstType::TSImportType,
        "TSIndexedAccessType" => AstType::TSIndexedAccessType,
        "TSIndexSignature" => AstType::TSIndexSignature,
        "TSInferType" => AstType::TSInferType,
        "TSInstantiationExpression" => AstType::TSInstantiationExpression,
        "TSInterfaceBody" => AstType::TSInterfaceBody,
        "TSInterfaceDeclaration" => AstType::TSInterfaceDeclaration,
        "TSInterfaceHeritage" => AstType::TSInterfaceHeritage,
        "TSIntersectionType" => AstType::TSIntersectionType,
        "TSIntrinsicKeyword" => AstType::TSIntrinsicKeyword,
        "TSJSDocNonNullableType" => AstType::TSJSDocNonNullableType,
        "TSJSDocNullableType" => AstType::TSJSDocNullableType,
        "TSLiteralType" => AstType::TSLiteralType,
        "TSMappedType" => AstType::TSMappedType,
        "TSMethodSignature" => AstType::TSMethodSignature,
        "TSModuleBlock" => AstType::TSModuleBlock,
        "TSModuleDeclaration" => AstType::TSModuleDeclaration,
        "TSNamedTupleMember" => AstType::TSNamedTupleMember,
        "TSNamespaceExportDeclaration" => AstType::TSNamespaceExportDeclaration,
        "TSNeverKeyword" => AstType::TSNeverKeyword,
        "TSNonNullExpression" => AstType::TSNonNullExpression,
        "TSNullKeyword" => AstType::TSNullKeyword,
        "TSNumberKeyword" => AstType::TSNumberKeyword,
        "TSObjectKeyword" => AstType::TSObjectKeyword,
        "TSOptionalType" => AstType::TSOptionalType,
        "TSParameterProperty" => AstType::TSParameterProperty,
        "TSParenthesizedType" => AstType::TSParenthesizedType,
        "TSPropertySignature" => AstType::TSPropertySignature,
        "TSQualifiedName" => AstType::TSQualifiedName,
        "TSRestType" => AstType::TSRestType,
        "TSSatisfiesExpression" => AstType::TSSatisfiesExpression,
        "TSStringKeyword" => AstType::TSStringKeyword,
        "TSSymbolKeyword" => AstType::TSSymbolKeyword,
        "TSTemplateLiteralType" => AstType::TSTemplateLiteralType,
        "TSThisType" => AstType::TSThisType,
        "TSTupleType" => AstType::TSTupleType,
        "TSTypeAliasDeclaration" => AstType::TSTypeAliasDeclaration,
        "TSTypeAnnotation" => AstType::TSTypeAnnotation,
        "TSTypeAssertion" => AstType::TSTypeAssertion,
        "TSTypeLiteral" => AstType::TSTypeLiteral,
        "TSTypeOperator" => AstType::TSTypeOperator,
        "TSTypeParameter" => AstType::TSTypeParameter,
        "TSTypeParameterDeclaration" => AstType::TSTypeParameterDeclaration,
        "TSTypeParameterInstantiation" => AstType::TSTypeParameterInstantiation,
        "TSTypePredicate" => AstType::TSTypePredicate,
        "TSTypeQuery" => AstType::TSTypeQuery,
        "TSTypeReference" => AstType::TSTypeReference,
        "TSUndefinedKeyword" => AstType::TSUndefinedKeyword,
        "TSUnionType" => AstType::TSUnionType,
        "TSUnknownKeyword" => AstType::TSUnknownKeyword,
        "TSVoidKeyword" => AstType::TSVoidKeyword,
        "UnaryExpression" => AstType::UnaryExpression,
        "UpdateExpression" => AstType::UpdateExpression,
        "VariableDeclaration" => AstType::VariableDeclaration,
        "VariableDeclarator" => AstType::VariableDeclarator,
        "WhileStatement" => AstType::WhileStatement,
        "WithStatement" => AstType::WithStatement,
        "YieldExpression" => AstType::YieldExpression,
        "Hashbang" => AstType::Hashbang,
        "TSJSDocUnknownType" => AstType::TSJSDocUnknownType,
        "V8IntrinsicExpression" => AstType::V8IntrinsicExpression,
        _ => AstType::UnknownAstType,
    }
}
