//! Newtype index IDs for the IR arena.
//!
//! Each ID is a `NonMaxU32`-backed type generated by
//! `oxc_index::define_nonmax_u32_index_type!`, the same shape oxc uses
//! in its `oxc_semantic::ScopingInner` arena. `Option<*Id>` is therefore
//! the same size as `u32` (the niche optimisation), which keeps the
//! arena dense.

oxc_index::define_nonmax_u32_index_type! {
    /// Arena index for a `ScopeData` in `IrArena::scopes`.
    pub struct ScopeId;
}

oxc_index::define_nonmax_u32_index_type! {
    /// Arena index for a `VariableData` in `IrArena::variables`.
    pub struct VariableId;
}

oxc_index::define_nonmax_u32_index_type! {
    /// Arena index for a `ReferenceData` in `IrArena::references`.
    pub struct ReferenceId;
}

oxc_index::define_nonmax_u32_index_type! {
    /// Arena index for a `DefinitionData` in `IrArena::definitions`.
    pub struct DefinitionId;
}
