export const NODE_KIND = {
  LegacyVariable: "LegacyVariable",
  LegacyFunctionName: "LegacyFunctionName",
  LegacyClassName: "LegacyClassName",
  LegacyParameter: "LegacyParameter",
  LegacyCatchClause: "LegacyCatchClause",
  LegacyImportBinding: "LegacyImportBinding",
  SyntheticImplicitGlobal: "SyntheticImplicitGlobal",
  LegacyWriteOp: "LegacyWriteOp",
  LegacyReturnUse: "LegacyReturnUse",
  SyntheticIfStatementTest: "SyntheticIfStatementTest",
  LegacySwitchDiscriminant: "LegacySwitchDiscriminant",
  SyntheticWhileStatementTest: "SyntheticWhileStatementTest",
  SyntheticDoWhileStatementTest: "SyntheticDoWhileStatementTest",
  LegacyForTest: "LegacyForTest",
  SyntheticModuleSink: "SyntheticModuleSink",
  SyntheticModuleSource: "SyntheticModuleSource",
  SyntheticImportIntermediate: "SyntheticImportIntermediate",
  SyntheticExpressionStatement: "SyntheticExpressionStatement",
  SyntheticBeyondDepth: "SyntheticBeyondDepth",
} as const;
export type NodeKind = (typeof NODE_KIND)[keyof typeof NODE_KIND];
