export const NODE_KIND = {
  LegacyVariable: "LegacyVariable",
  LegacyFunctionName: "LegacyFunctionName",
  LegacyClassName: "LegacyClassName",
  LegacyParameter: "LegacyParameter",
  LegacyCatchClause: "LegacyCatchClause",
  LegacyImportBinding: "LegacyImportBinding",
  LegacyImplicitGlobalVariable: "LegacyImplicitGlobalVariable",
  LegacyWriteOp: "LegacyWriteOp",
  LegacyReturnUse: "LegacyReturnUse",
  LegacyIfTest: "LegacyIfTest",
  LegacySwitchDiscriminant: "LegacySwitchDiscriminant",
  LegacyWhileTest: "LegacyWhileTest",
  LegacyDoWhileTest: "LegacyDoWhileTest",
  LegacyForTest: "LegacyForTest",
  SyntheticModuleSink: "SyntheticModuleSink",
  SyntheticModuleSource: "SyntheticModuleSource",
  LegacyImportIntermediate: "LegacyImportIntermediate",
  LegacyExpressionStatement: "LegacyExpressionStatement",
  SyntheticBeyondDepth: "SyntheticBeyondDepth",
} as const;
export type NodeKind = (typeof NODE_KIND)[keyof typeof NODE_KIND];
